server:
  port: 80
spring:
  datasource:
    continue-on-error: true
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://db.loacg.com:9522/sync_github?&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: opendev
    password: ddhqnXvyXb2aRv4G
    # 初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

logging:
  level:
    root: warn
    org.springframework: warn
    org.hibernate: warn
    org.apache.catalina: warn
    com.loacg: info
    org.telegram: warn
  path: /var/log/sync-github/
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %clr([%thread]){blue} %-5level %clr(%logger{50}){green} - %msg%n"

github:
  sync:
    basePath: /data/web/mirrors/